modLoader = "javafml"
loaderVersion = "[2,)"
license = "Apache 2.0"
issueTrackerURL = "https://github.com/Luligabi1/Incantationem/issues"
[[mods]]
modId = "incantationem"
version = "${version}"
displayName = "Incantationem"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/incantationem"
logoFile = "icon.png"
authors = "Luligabi1"
credits = "dummy"
description = "dummy"
[[mixins]]
config = "incantationem-common.mixins.json"
[[dependencies.incantationem]]
modId = "architectury"
type = "required"
versionRange = "[11,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.incantationem]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.incantationem]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"