modLoader = "javafml"
loaderVersion = "[2,)"
license = "Apache 2.0"
issueTrackerURL = "https://github.com/Luligabi1/Incantationem/issues"
[[mods]]
modId = "incantationem"
version = "2.0"
displayName = "Incantationem"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/incantationem"
logoFile = "icon.png"
authors = "Luligabi1"
credits = "With contributions by Superkat32 || With translations by ghost, 4444Zao9 and UpcraftLP"
description = "Introduces vanilla+, fully configurable enchantments"
[[mixins]]
config = "incantationem-common.mixins.json"
[[dependencies.incantationem]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.incantationem]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.incantationem]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"