plugins {
    id 'fabric-loom' version '1.2-SNAPSHOT'
    id 'me.modmuss50.mod-publish-plugin' version '0.4.5'
    id 'maven-publish'
}

archivesBaseName = project.archives_base_name
version = project.mod_version

def modName = project.mod_name

repositories {
    maven { url = "https://jitpack.io" }
    maven { url = "https://maven.isxander.dev/releases/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "com.github.LlamaLad7:MixinExtras:${project.mixinextras_version}"
    include "com.github.LlamaLad7:MixinExtras:${project.mixinextras_version}"
    annotationProcessor "com.github.LlamaLad7:MixinExtras:${project.mixinextras_version}"

    include modImplementation("dev.isxander.yacl:yet-another-config-lib-fabric:${project.yacl_version}") {
        transitive(false)
    }

    modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
    modRuntimeOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

base {
    archivesName = project.archives_base_name
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}"}
    }
}

publishMods {
    file = remapJar.archiveFile
    displayName = (project.mod_version as String)
    type = STABLE
    modLoaders.add("fabric")
    changelog =
    """
- Added 3 new enchantments;
    - Deflection;
    - Fuse Shot;
    - Water Slash.
- Added Curse of Shrieking;
- Incompatible enchantments and curses are now defined through an enchantment tag.
    """

    curseforge {
        projectId = project.curseforge_id
        projectSlug = project.curseforge_slug
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        minecraftVersions.add(project.minecraft_version)

        requires {
            slug = "fabric-api"
        }
    }

    modrinth {
        projectId = project.modrinth_id
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(project.minecraft_version)

        requires {
            slug = "fabric-api"
        }
    }


    discord {
        webhookUrl = providers.environmentVariable("CAFETERIA_MOD_RELEASE_WEBHOOK")
        username = modName
        avatarUrl = project.webhook_icon

        content = changelog.map { "# " + (modName as String) + " " + (project.mod_version as String) + " has been released \n" + it}
    }
}