# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# Check these on https://modmuss50.me/fabric.html
minecraft_version=1.19.3
yarn_mappings=1.19.3+build.2
loader_version=0.14.11

# Mod Properties
mod_version=1.2+1.19.3
maven_group=me.luligabi
archives_base_name=incantationem

# Dependencies
# Check this on https://modmuss50.me/fabric.html
fabric_version=0.68.1+1.19.3
mixinextras_version=0.0.11
yacl_version=2.0.0
modmenu_version=5.0.0-alpha.4

# Publishing
curseforge_id=483166
modrinth_id=ZmRxbKUp
